site_name: The Notebook

# Nav bar
nav:
  - home: index.md
  - projects: projects.md
  - git: git.md
  - hw:
    - raspberry: hw/raspberrypi3.md
  - languages: 
    - python: langs/python.md
  - web:
    - django: web/django.md
    - rails: web/rails.md

# Repo info
repo_url: https://github.com/sannae/the-notebook

# Graphics
theme:
  name: material
  favicon: images/logo.png
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/library
  # custom_dir: material

  # Color theme
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  # Navigation features
  features:
    - navigation.tabs 
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  # Table of content
  - toc:
      permalink: ⚓︎
  # tags support
  - meta
  # buttons
  - attr_list
  # tabs
  - pymdownx.tabbed
  - pymdownx.superfences
  # admonitions
  - admonition
  - pymdownx.details
  # icons
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # checklist
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.arithmatex:
      generic: true