# Project information
site_name: The Notebook
site_url: https://sannae.github.io/the-notebook
site_author: sannae
site_description: Welcome to my online knowledge base!

# Nav bar
nav:
  - home: index.md
  #- projects: projects.md
  - cloud:
    - aws: cloud/aws.md
    - azure: cloud/azure.md
    - azure-pipelines: cloud/azure-pipelines.md
    - docker: cloud/docker.md
    - oracle: cloud/oracle.md
    - vagrant: cloud/vagrant.md
    - windows: cloud/windows.md
  - db:
    - mysql: db/mysql.md
    - postgres: db/postgres.md
    - sqlserver: db/sqlserver.md
  - dev: 
    - git: dev/git.md
    - github: dev/github.md
    #- gitpod: dev/gitpod.md
  - hw:
    - raspberry: hw/raspberrypi3.md
  - langs: 
    # - bash: langs/bash.md
    - javascript: langs/javascript.md
    #- powershell: langs/powershell.md
    - python: langs/python.md
  - web:
    - aspnetcore: web/aspnetcore.md
    - django: web/django.md
    - rails: web/rails.md
    # - reactjs: web/reactjs.md

# Repo info
repo_url: https://github.com/sannae/the-notebook

# Graphics
theme:
  name: material
  favicon: images/logo.png
  language: en

  # Themes
  font:
    text: Roboto
    code: Roboto Mono

  # Icons
  icon:
    repo: fontawesome/brands/git-alt
    logo: material/library

  # Color theme
  palette:
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  # Navigation features
  features:
    - navigation.tabs 
    - navigation.indexes
    - navigation.top

# Extensions
markdown_extensions:
  # Table of content
  - toc:
      permalink: ⚓︎
  # tags support
  - meta
  # buttons
  - attr_list
  # tabs
  - pymdownx.tabbed
  - pymdownx.superfences
  # admonitions
  - admonition
  - pymdownx.details
  # icons
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # checklist
  - pymdownx.tasklist:
      custom_checkbox: true
  - def_list
  - pymdownx.arithmatex:
      generic: true
