name: ci 

# Trigger only on pushing to main
on:
  push:
    branches: 
      - master
      - main
  
# Build with GitHub Actions runner
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    
      # Checkout latest commit
      - uses: actions/checkout@v2
      
      # Setup Python
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      
      # Install requirements
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt
          pip install mkdocs-material
      
      # Deploy mkdocs
      - run: mkdocs gh-deploy --force
